### PR TITLE
Users created before this validation should be updateable

### PR DESCRIPTION
**Pull request by Fernan2**

### CODE REVIEW

**Comment by 007lva** [comment]
:+1:

**Comment by maxvlc** [comment]
:+1:

**Comment by d2bit** [comment]
I don't get it :confused:
A user will be able to change her email to a banned-domain one?

**Comment by Fernan2** [comment]
People only uses those domains for first registration purposes, there is no problem on allowing them later because nobody will do it. 

There is another valid approach: to apply the validation for users created after 03-oct-2014, when it started to apply in Rankia, but doing on create seems me cleaner and won't be a problem (and anyway, it will allow banned domains for older users).

**Comment by Fernan2** [comment]
Tests passing... @d2bit , is this fine for you?

**Comment by d2bit** [comment]
:+1:

**Pull request merged**
